server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5   #每5S发送一次心跳
    service-url:
      defaultZone: http://localhost:10086/eureka    #注册中心
zuul:
  prefix: /api     #路由前缀
  routes:
    item-service: /item/**   #商品微服务的映射路径
    search-service: /search/** #搜索的微服务
    user-service: /user/** #用户微服务
    auth-service: /auth/**
  ignored-patterns: /upload/**
  ignored-services:
    - leyou-upload    #忽略upload的服务

