server:
  port: 8084
spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.241.131
    username: leyou
    password: 2580
    virtual-host: /
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5   #每5S发送一次心跳
    lease-expiration-duration-in-seconds: 10  #10S不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}